app/__init__.py
from flask import Flask
from .site.routes import site
from config import Config
from .authentication.routes import auth
from .api.routes import api
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from models import db as root_db, login_manager, ma
from flask_cors import CORS
from helpers import JSONEncoder

app = Flask(__name__)
CORS(app)

app.json_encoder = JSONEncoder
app.config.from_object(Config)
root_db.init_app(app)
login_manager.init_app(app)
ma.init_app(app)
migrate = Migrate(app, root_db)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)

app/api/routes.py
from flask import Blueprint, request, jsonify
from helpers import token_required
from models import User, Car, car_schema, cars_schema, db

api = Blueprint('api', __name__, url_prefix='/api')

@api.route('/getdata')
def getdata():
    return { 'yoo': 'wee'}

@api.route('/cars', methods = ['POST'])
@token_required
def create_car(current_user_token):
    make = request.json['make']
    model = request.json['model']
    sale_price = request.json['sale_price']
    color = request.json['color']
    year = request.json['year']
    new_used = request.json['new_used']
    user_token = current_user_token.token

    car = Car(make,model,sale_price,color,year,new_used,user_token = user_token)

    db.session.add(car)
    db.session.commit()

    response = car_schema.dump(car)
    return jsonify(response)

@api.route('/cars', methods = ['GET'])
@token_required
def get_cars(current_user_token):
    owner = current_user_token.token
    cars = Car.query.filter_by(user_token = owner).all()
    response = cars_schema.dump(cars)
    return jsonify(response)

@api.route('/cars/<id>', methods = ['GET'])
@token_required
def get_car(current_user_token, id):
    car = Car.query.get(id)
    response = car_schema.dump(car)
    return jsonify(response)
    
# Update endpoint
@api.route('/cars/<id>', methods = ['POST', 'PUT'])
@token_required
def update_car(current_user_token, id):
    car = Car.query.get(id) 
    car.make = request.json['make']
    car.model = request.json['model']
    car.sale_price = request.json['sale_price']
    car.color = request.json['color']
    car.year = request.json['year']
    car.new_used = request.json['new_used']
    car.user_token = current_user_token.token

    db.session.commit()
    response = car_schema.dump(car)
    return jsonify(response)

@api.route('/cars/<id>', methods = ['DELETE'])
@token_required
def delete_car(current_user_token, id):
    car = Car.query.get(id)
    db.session.delete(car)
    db.session.commit()
    response = car_schema.dump(car)
    return jsonify(response)

app/authentication/routes.py
from forms import UserLoginForm
from models import User, User, db, check_password_hash
from flask import Blueprint, render_template, request, redirect, url_for, flash

from flask_login import login_user, logout_user, LoginManager, current_user, login_required

auth = Blueprint('auth', __name__, template_folder='auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email, password)

            user = User(email, password = password)
            db.session.add(user)
            db.session.commit()

            flash(f'You have successfully created a user account {email}', 'user-created')

            return redirect(url_for('site.home'))

    except:
        raise Exception('Invalid Form Data: Please Check Your Form Inputs')

    return render_template('signup.html',form = form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()

    try:

        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email,password)
            
            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successfully logged in: via email/password', 'auth-success')
                return redirect(url_for('site.home'))

 
            else:
                flash('Your email/password is incorrect', 'auth-failed')
                return redirect(url_for('auth.signin'))

    except:
        raise Exception('Invalid Form Data: Please Check Your Form!')

    return render_template('signin.html', form=form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

app/site/routes.py
from flask import Blueprint, render_template

site = Blueprint('site', __name__, template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')
    

@site.route('/profile')
def profile():
    return render_template('profile.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Car Inventory</title>
</head>
<body>
  <nav class="navbar navbar-expand navbar-light" style="background-color:blue">
    <div class="container-fluid">
      <a class="navbar-brand">ALL IN Inventory</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" aria-current="page" href="{{ url_for('site.home') }}">Home</a>
          <a class="nav-link" href="#">Features</a>
          <a class="nav-link active" href="{{ url_for('site.profile') }}">Profile</a>
          {% if current_user.is_authenticated %}
          <a class="nav-link active" href="{{ url_for('auth.logout') }}">Log out</a>
          {% else %}
          <a class="nav-link active"  href="{{ url_for('auth.signin') }}">Sign In</a>
          <a class="nav-link active" href="{{ url_for('auth.signup') }}">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>
      {% block content %}
      {% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Place Email Here...")}}
        </fieldset>

        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Place Password Here...")}}
        </fieldset>

        <!--Submit Button Area-->
        {{ form.submit_button(class = "btn btn-primary btn-block") }}
    </div>
</form>